Create how-to-use-memoization-in-react-better.md
mathpang/techpang pull request #1
Opened 2022-07-20 16:47 UTC by hsh2001

2022-07-21 03:36 UTC, dev-bban submitted a review, later dismissed
잘 읽었습니다👍
- `메모이제이션이라고도 한다.`에 (memoisation) 추가해도 좋을 것 같아요

2022-07-21 04:08 UTC, math-hsh requested changes

2022-07-21 04:08 UTC, math-hsh commented on react/how-to-use-memoization-in-react-better.md
> +이러한 특징은 함수, 배열, 객체 등 얕은 비교를 했을 떄 주소를 비교하는 값들을 `Props`로 사용했을 때 공통적으로 발생하는 문제입니다.
```suggestion
이러한 특징은 함수, 배열, 객체 등 얕은 비교를 했을 때 주소를 비교하는 값들을 `Props`로 사용했을 때 공통적으로 발생하는 문제입니다.
```

2022-07-21 04:08 UTC, math-hsh commented on react/how-to-use-memoization-in-react-better.md
> +위의 예시에서는 함수의 실제 로직은 변하지 않지만, 단지 다시 렌더링 될 때 함수가 다시 생성된다는 이유로 비교 연산을 했을 떄 거짓을 결과로 갖습니다.
```suggestion
위의 예시에서는 함수의 실제 로직은 변하지 않지만, 단지 다시 렌더링 될 때 함수가 다시 생성된다는 이유로 비교 연산을 했을 때 거짓을 결과로 갖습니다.
```

2022-07-21 04:08 UTC, math-hsh commented on react/how-to-use-memoization-in-react-better.md
> +> 메모이제이션(memoization)은 컴퓨터 프로그램이 동일한 계산을 반복해야 할 때, 이전에 계산한 값을 메모리에 저장함으로써 동일한 계산의 반복 수행을 제거하여 프로그램 실행 속도를 빠르게 하는 기술이다. 동적 계획법의 핵심이 되는 기술이다. 메모이제이션이라고도 한다. (- Wikipedia)
```suggestion
> 메모이제이션(memoization)은 컴퓨터 프로그램이 동일한 계산을 반복해야 할 때, 이전에 계산한 값을 메모리에 저장함으로써 동일한 계산의 반복 수행을 제거하여 프로그램 실행 속도를 빠르게 하는 기술이다. 동적 계획법의 핵심이 되는 기술이다. 메모이제이션(memoisation)이라고도 한다. (- Wikipedia)
```

2022-07-21 04:10 UTC, mathpangSangJoon approved these changes

2022-07-21 04:11 UTC, math-hsh approved these changes

2022-07-21 05:14 UTC, dev-bban approved these changes

2022-07-21 06:07 UTC, Dev-Young-Jae approved these changes

2022-07-22 04:06 UTC, wjlee-mathpang approved these changes

2022-07-24 07:09 UTC, hsh2001 reviewed
남균님의 리뷰
- 재미있는 제목을 써보면 어떨까요?
- 소제목끼리에 스토리가 있으면 좋을 것 같아요.

2022-07-24 07:22 UTC, mathpang-castlemo approved these changes
현재의 글을 읽을때 선행되어야 하는 지식("JS 얕은 비교와 깊은 비교", "React에서는 이벤트 핸들러도 함수다")들을 설명해주셔서 헷갈릴법한 부분을 잘 짚어주신거 갔습니다!

잘 읽었습니다

2022-08-26 01:32 UTC, merged